<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>af53c61d-7817-4205-938c-17f33877e6d9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.3.0" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.3.0" />
      <PackageReference Include="TagLibSharp" Version="2.2.0" />
  </ItemGroup>

</Project>
